### ISSUE TITLE
2 Mods no longer supported

### ISSUE THREAD

**Issue by johnpine1970** [Camora0/Wasteland-Reborn#4]
2 files:
**Colt Single Action Army - F4NV-47820-1-1-1602801790.rar](https://miami-premium.nexus-cdn.com/1151/47820/Colt%20Single%20Action%20Army%20-%20F4NV-47820-1-1-1602801790.rar?md5=vpcjRow_Msd2xyhY_nhGnw&expires=1718554370&user_id=1263637)** 

and 

**[F4NV-AMR_v1.5.1-36922-v1-5-1-1573930226.7z](https://miami-premium.nexus-cdn.com/1151/36922/F4NV-AMR_v1.5.1-36922-v1-5-1-1573930226.7z?md5=VDh4i7WNXCuKvatzrML-HQ&expires=1718554587&user_id=1263637)** 

are archived and will cause the Wabbajack installer to fail.
Respectfully,
JP

**Comment by ElisPlayz** [comment]
Correct. These files are to be obtained from the discord linked in the install section under "Could not download..."
